"""initial

Revision ID: 5f5e521f73a1
Revises: 
Create Date: 2022-08-18 12:30:54.430692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f5e521f73a1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("template_type", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_template_id"), "message_template", ["id"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("scope", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "campaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("via_sms", sa.Boolean(), nullable=False),
        sa.Column("via_email", sa.Boolean(), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("audience_number", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaign_id"), "campaign", ["id"], unique=False)
    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("composite_key", sa.String(length=50), nullable=True),
        sa.Column("student_id", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("preferred_email", sa.String(length=255), nullable=True),
        sa.Column("crc_email", sa.String(length=255), nullable=True),
        sa.Column("application_email", sa.String(length=255), nullable=True),
        sa.Column("day_phone_number", sa.String(length=20), nullable=True),
        sa.Column("evening_phone_number", sa.String(length=20), nullable=True),
        sa.Column("major", sa.String(length=255), nullable=True),
        sa.Column("cac", sa.String(length=255), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=50), nullable=True),
        sa.Column("race_ethnicity", sa.String(length=50), nullable=True),
        sa.Column("new_student", sa.String(length=50), nullable=True),
        sa.Column("athlete", sa.String(length=50), nullable=True),
        sa.Column("puente", sa.String(length=50), nullable=True),
        sa.Column("diop", sa.String(length=50), nullable=True),
        sa.Column("reported_disability", sa.String(length=50), nullable=True),
        sa.Column("income_level_self_reported", sa.String(length=255), nullable=True),
        sa.Column("bog", sa.String(length=255), nullable=True),
        sa.Column("cal_works", sa.String(length=50), nullable=True),
        sa.Column("eops", sa.String(length=50), nullable=True),
        sa.Column("care", sa.String(length=50), nullable=True),
        sa.Column("homeless", sa.String(length=50), nullable=True),
        sa.Column("need_based_federal_aid", sa.String(length=50), nullable=True),
        sa.Column("completed_units", sa.Float(), nullable=True),
        sa.Column("gpa", sa.Float(), nullable=True),
        sa.Column("units_completed_including_district", sa.Float(), nullable=True),
        sa.Column("enrolled_districtwide", sa.String(length=50), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contact_composite_key"), "contact", ["composite_key"], unique=True
    )
    op.create_index(
        op.f("ix_contact_day_phone_number"),
        "contact",
        ["day_phone_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_evening_phone_number"),
        "contact",
        ["evening_phone_number"],
        unique=False,
    )
    op.create_index(op.f("ix_contact_id"), "contact", ["id"], unique=False)
    op.create_index(
        op.f("ix_contact_preferred_email"), "contact", ["preferred_email"], unique=False
    )
    op.create_table(
        "contact_csv",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("s3_uri", sa.String(length=255), nullable=True),
        sa.Column("s3_bucket", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contact_csv_id"), "contact_csv", ["id"], unique=False)
    op.create_table(
        "custom_message_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["message_template.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "default_message_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["message_template.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("default_message_template")
    op.drop_table("custom_message_template")
    op.drop_index(op.f("ix_contact_csv_id"), table_name="contact_csv")
    op.drop_table("contact_csv")
    op.drop_index(op.f("ix_contact_preferred_email"), table_name="contact")
    op.drop_index(op.f("ix_contact_id"), table_name="contact")
    op.drop_index(op.f("ix_contact_evening_phone_number"), table_name="contact")
    op.drop_index(op.f("ix_contact_day_phone_number"), table_name="contact")
    op.drop_index(op.f("ix_contact_composite_key"), table_name="contact")
    op.drop_table("contact")
    op.drop_index(op.f("ix_campaign_id"), table_name="campaign")
    op.drop_table("campaign")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_message_template_id"), table_name="message_template")
    op.drop_table("message_template")
    # ### end Alembic commands ###
