services:

  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT_DOCKER}"
    volumes:
      - .:/code
    command: [ "python", "main.py" ]
    depends_on:
      - db

  db:
    image: mysql
    restart: unless-stopped
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "${DB_PORT}:${DB_DOCKER_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -P ${DB_DOCKER_PORT} -p${DB_PASSWORD} | grep 'mysqld is alive' || exit 1"
        ]

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=example