services:

  api:
    build: .
    container_name: ${PROJECT_NAME}_API
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT_DOCKER}"
    volumes:
      - .:/code
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "${API_PORT_DOCKER}",
        "--reload"
      ]
